server:
  port: 9021

spring:
  application:
    name: ddms-interface
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.wmcloud.top:3306/datadictionary?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=true&testOnBorrow=true
    username: mysqlroot
    password: mysqlroot
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true