server:
  port: 9009

spring:
  application:
    name: workers-view
  thymeleaf:
    ###使页面校验轻松
    mode: LEGACYHTML5
    ###将页面缓存关闭
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka