server:
  port: 9001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lizetuty/elective_config.git
          search-paths:
          username:
          password:
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
